spring:
  application:
    name: config-server
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 9090
  servlet:
    session:
      cookie:
        http-only: true
  error:
    include-message: always

logging:
  file:
    name: log/duman.log

management:
  endpoint:
    routes:
      enabled: true
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

---

spring:
  profiles: dev
  data:
    mongodb:
      uri: ${mongodb.logger.uri:${mongodb.uri:mongodb://localhost:27017}}
      database: duman
  redis:
    host: localhost
    port: 7001

logging:
  level:
    root: info

---

spring:
  profiles: test
  data:
    mongodb:
      uri: ${mongodb.logger.uri:${mongodb.uri:mongodb://mongo:27017}}
      database: duman
  redis:
    host: localhost
    port: 7001

logging:
  level:
    root: info

---

spring:
  profiles: prod
  data:
    mongodb:
      uri: ${mongodb.logger.uri:${mongodb.uri:mongodb://mongo:27017}}
      database: duman
  redis:
    host: localhost
    port: 7001

logging:
  level:
    root: info
